# Generated by Django 4.1.4 on 2022-12-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_rename_portfoliolink_soshialnetwork_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='soshialnetwork',
            options={'verbose_name': 'social network', 'verbose_name_plural': 'social networks'},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Soshial_network',
            new_name='soshial_network',
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='sss', help_text='City where you live', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='biography',
            field=models.TextField(help_text='Tell everyone about yourself'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='skill',
            field=models.ManyToManyField(help_text='things you can do, techs you know', to='user_profile.skill'),
        ),
    ]
